### ISSUE TITLE
Failed to load the plugin

### ISSUE THREAD

**Issue by SirSaliver** [tabibyte/obsifetch#4]
MacOS 15.0.1 on Macbook Pro M3. After putting the downloaded files in the correct directory, the plugin appeared in the `Settings -> Third-party plugin -> Installed plugins`, but it cannot be turned on. The alert: `Failed to load plugin "obsifetch"`.

**Comment by marc-alexis-com** [comment]
Me too, I can't make it work.
Ive copied  **main.ts** (in the ReadMe, it says **main.js,** but i can't find it), **manifest.json** and **styles.css**

**Comment by tabibyte** [comment]
> Me too, I can't make it work. Ive copied **main.ts** (in the ReadMe, it says **main.js,** but i can't find it), **manifest.json** and **styles.css**

Hi @marc-alexis-com, you should get main.js file from [Releases page](https://github.com/tabibyte/obsifetch/releases). Try that, if it still doesn't work, I'm working on Mac compatibility. Will update the README.md

**Comment by tabibyte** [comment]
[test_mac.zip](https://github.com/user-attachments/files/17788439/test_mac.zip)

hey @SirSaliver, I couldn't get any mac to work with, but changed some code, try this one:
- disable the plugin in the settings
- delete the old files from obsifetch folder
- replace it with these, load the plugin and try again

let me know if this works.

**Comment by SirSaliver** [comment]
Problem solved by @tabibyte. Thank you genius!
