### ISSUE TITLE
Support non-desktop

### ISSUE THREAD

**Issue by MP3Martin** [tabibyte/obsifetch#8]
Nice plugin. Is there any reason that it is [only allowed on desktop](https://github.com/tabibyte/obsifetch/blob/dfdd22d539719c5e68c6d441372708c1452aeaf7/manifest.json#L9)?

I'm not sure if i remember correctly, but i remember previously installing the plugin manually on my (Android) phone before it was available on the community plugins page, and it worked fine.

**Comment by tabibyte** [comment]
thank you! after adding some extra features, it broke somehow, so I decided to restrict it for now. I'm working on it!

**Comment by tabibyte** [comment]
Hi, fixed it :) @MP3Martin

**Comment by MP3Martin** [comment]
> Hi, fixed it :) @MP3Martin 

Amazing, thank you
